### ISSUE TITLE
Clear All Data In Database

### ISSUE THREAD

**Issue by hunter-waite** [jarmeister99/csc307-doit#43]
Be able to clear all data in the database for a specific user so that they can start fresh.

**Comment by jarmeister99** [comment]
Finished 30 min

**Comment by hunter-waite** [comment]
Estimated Time: About 1 hr total

**Comment by hunter-waite** [comment]
Frontend Finished Time: 30 mins
Backend Finished Time: 30 mins
Total Time: 1 hour
